### ISSUE TITLE
BUG: Android Support

### ISSUE THREAD

**Issue by matthiasbruns** [firebase/firebase-token-generator-java#12]
````
java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)
            at com.firebase.security.token.JWTEncoder.encodeJson(JWTEncoder.java:64)
            at com.firebase.security.token.JWTEncoder.getCommonHeader(JWTEncoder.java:57)
            at com.firebase.security.token.JWTEncoder.encode(JWTEncoder.java:30)
            at com.firebase.security.token.TokenGenerator.computeToken(TokenGenerator.java:96)
            at com.firebase.security.token.TokenGenerator.createToken(TokenGenerator.java:88)
            at com.firebase.security.token.TokenGenerator.createToken(TokenGenerator.java:37)
````

Dependencies in build.gradle

````
compile 'commons-codec:commons-codec:1.7'
compile 'org.json:json:20090211'
compile 'com.firebase:firebase-client-android:2.3.1'
compile 'com.firebase:firebase-token-generator:2.0.0'
````

Why don't you use the Android Base64 Utils?

**Comment by puf** [comment]
One good reason would be that you should never generate tokens on a client-device, i.e. Android. Generating a token requires the use of the Secret of your Firebase application. If you generate the token in an Android app, it means your Secret is also in that APK, where malicious users can get it and use it to gain unrestricted access to your Firebase back-end.

**Comment by robertdimarco** [comment]
@matthiasbruns At least for the time being, what @puf said is correct. This is intended to be a strictly-server-side library. I can see some utility in this running in Android for the purposes of testing, but I believe the risks there outweigh the benefits.
