### ISSUE TITLE
No static method encodeBase64URLSafeString([B)Ljava/lang/String

### ISSUE THREAD

**Issue by antoniomerlin** [firebase/firebase-token-generator-java#13]
` java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)
                                                       at com.cinchsports.cinchapp.Utils.JWTEncoder.encodeJson(JWTEncoder.java:62)
                                                       at com.cinchsports.cinchapp.Utils.JWTEncoder.getCommonHeader(JWTEncoder.java:55)
                                                       at com.cinchsports.cinchapp.Utils.JWTEncoder.encode(JWTEncoder.java:28)
                                                       at com.cinchsports.cinchapp.Utils.TokenGenerator.computeToken(TokenGenerator.java:94)
                                                       at com.cinchsports.cinchapp.Utils.TokenGenerator.createToken(TokenGenerator.java:86)
                                                       at com.cinchsports.cinchapp.Utils.TokenGenerator.createToken(TokenGenerator.java:35)
                                                       at com.cinchsports.cinchapp.Core_Activity.Messages_Activity.onCreate(Messages_Activity.java:66)
                                                       at android.app.Activity.performCreate(Activity.java:5953)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)`

**Comment by akonior** [comment]
`java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
03-17 11:18:34.308  3097  3097 E AndroidRuntime: 	at com.firebase.security.token.JWTEncoder.encodeJson(JWTEncoder.java:64)
03-17 11:18:34.308  3097  3097 E AndroidRuntime: 	at com.firebase.security.token.JWTEncoder.getCommonHeader(JWTEncoder.java:57)
03-17 11:18:34.308  3097  3097 E AndroidRuntime: 	at com.firebase.security.token.JWTEncoder.encode(JWTEncoder.java:30)
03-17 11:18:34.308  3097  3097 E AndroidRuntime: 	at com.firebase.security.token.TokenGenerator.computeToken(TokenGenerator.java:96)
03-17 11:18:34.308  3097  3097 E AndroidRuntime: 	at com.firebase.security.token.TokenGenerator.createToken(TokenGenerator.java:88)
03-17 11:18:34.308  3097  3097 E AndroidRuntime: 	at com.firebase.security.token.TokenGenerator.createToken(TokenGenerator.java:37)`

**Comment by mikelehen** [comment]
Please see https://github.com/firebase/firebase-token-generator-java/issues/10

**Comment by colinrtwhite** [comment]
> Unless you have a very uncommon edge-case (a server you control running on Android)

The linked issue doesn't say how to fix the problem if we do have a server we control running Android.

**Comment by mikelehen** [comment]
The code is open source.  You can swap in a functioning base64 implementation if you really want / need to...
